name: Expose demo secret
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  update_secret:
    name: update secret
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Update secret
        run: |
          mkdir -p demo-secrets
          code=$(tr -dc 0-9 </dev/urandom | head -c 30)
          echo "code='ENIGMA-$code'" >> secrets.py
          cp -rf secrets.py ./demo-secrets/
      - name: commit changes
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./demo-secrets/
          git commit -m "Update demo secret"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
        
            